### ISSUE TITLE
application does not run

### ISSUE THREAD

**Issue by mylinttrap** [barrucadu/bookdb#19]
I've run this in my local docker using the python:3.8 image. 

When I run the app, i get this page: The search server is unavailable. Try again in a minute or two.
I did pip install -y requirements-freeze.txt
basically everything that was in the Dockerfile. 

This is after editing serve.py because the redirect breaks the site completely.
from : BASE_URI = os.getenv("BASE_URI", "http://bookdb.nyarlathotep")
to: BASE_URI = os.getenv("BASE_URI", "http://192.168.1.76:8888")

After that I gave up. I dont think this is a repeatable install inside or outside docker. 
You also have a port variabl 9200 that is on localhost but not open or called to be open. so i opened that on my container. 

I like the project idea... hopefully you can make it so that it works correctly. 
I cant spend more time trying to get it to work :(

**Comment by barrucadu** [comment]
You don't need to edit the source to change the `BASE_URI`, you can just set that environment variable (same with `ES_HOST`, `COVER_DIR`, and `ALLOW_WRITES`).

It's looking for an elasticsearch server at `ES_HOST`, which is `http://localhost:9200` by default.  Try this docker-compose file out:

```yaml
version: '3'

services:
  bookdb:
    build: .
    restart: always
    environment:
      ALLOW_WRITES: "1"
      BASE_URI: "http://192.168.1.76:8888"
      COVER_DIR: "/bookdb-covers"
      ES_HOST: "http://db:9200"
    networks:
      - bookdb
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - bookdb_covers:/bookdb-covers
    depends_on:
      - db

  db:
    image: elasticsearch:7.6.2
    restart: always
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    networks:
      - bookdb
    volumes:
      - bookdb_esdata:/usr/share/elasticsearch/data

networks:
  bookdb:
    external: false

volumes:
  bookdb_covers:
  bookdb_esdata:
```
